// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsnxvvpzwzaiveykzlnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdzbnh2dnB6d3phaXZleWt6bG53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDE0MTIsImV4cCI6MjA2NDE3NzQxMn0.0vTOunFjWp2WSty9fVqVtY2D63kVwET3MhfhhJGwRvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);